import { HardSkill } from 'src/app/models/skills.model';

export const HardSkillList: HardSkill[] = [
  {
    id: 58,
    name: 'HTML',
    type: 'frontend',
    image: 'html.svg',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    id: 59,
    name: 'CSS',
    type: 'frontend',
    image: 'css.svg',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  {
    id: 60,
    name: 'Javascript',
    type: 'frontend',
    image: 'javascript.svg',
    url: 'https://developer.mozilla.org/en-US/docs/Web/javascript',
  },
  {
    id: 61,
    name: 'Typescript',
    type: 'frontend',
    image: 'typescript.svg',
    url: 'https://www.typescriptlang.org/',
  },
  {
    id: 62,
    name: 'Angular',
    type: 'frontend',
    image: 'angular.svg',
    url: 'https://angular.io/',
  },
  {
    id: 63,
    name: 'Sass',
    type: 'frontend',
    image: 'sass.svg',
    url: 'https://sass-lang.com/',
  },
  {
    id: 64,
    name: 'Bootstrap',
    type: 'frontend',
    image: 'bootstrap.svg',
    url: 'https://getbootstrap.com/',
  },
  {
    id: 65,
    name: 'Nest Js',
    type: 'backend',
    image: 'nestjs.svg',
    url: 'https://nestjs.com/',
  },
  {
    id: 67,
    name: 'Node Js',
    type: 'backend',
    image: 'nodejs.svg',
    url: 'https://nodejs.org/',
  },
  {
    id: 68,
    name: 'MySQL',
    type: 'backend',
    image: 'mysql.svg',
    url: 'https://www.mysql.com/',
  },
  {
    id: 69,
    name: 'Visual Studio Code',
    type: 'tool',
    image: 'vscode.svg',
    url: 'https://code.visualstudio.com/',
  },
  {
    id: 71,
    name: 'Git',
    type: 'tool',
    image: 'git.svg',
    url: 'https://git-scm.com/',
  },
  {
    id: 72,
    name: 'Npm',
    type: 'tool',
    image: 'npm.svg',
    url: 'https://www.npmjs.com/',
  },
  {
    id: 75,
    name: 'Firebase',
    type: 'tool',
    image: 'firebase.svg',
    url: 'https://firebase.google.com/',
  },
  {
    id: 76,
    name: 'Postman',
    type: 'tool',
    image: 'postman.svg',
    url: 'https://www.postman.com/',
  },
];
